name: Github actions demo

run-name: ${{ github.actor }} is testing out github actions

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "Hello, world!" > hello.log
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hello-file.log
          path: hello.log