name: Github actions demo

run-name: ${{ github.actor }} is testing out github actions

on:
  pull_request:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: 'actions/checkout@v4'
      - name: Check for Version Bump
        uses: bachmacintosh/need-npm-package-version-bump@v1