name: Github actions demo

run-name: ${{ github.actor }} is testing out github actions

on:
  workflow_dispatch:
  push: 

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: 'actions/checkout@v4'
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth with Tyro Private NPM Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > "${HOME}/.npmrc"
          echo "@linkrjr:registry=https://npm.pkg.github.com" >> "${HOME}/.npmrc"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> "${HOME}/.npmrc"

      - name: Bump Package Version & Publish
        uses: 'g33kio/npm-version-bump@master'  