name: Github actions demo

run-name: ${{ github.actor }} is testing out github actions

on:
  workflow_dispatch:
  push: 
    
jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: 'actions/checkout@v4'
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Bump Package Version & Publish
        uses: 'g33kio/npm-version-bump@master'  