name: Github actions demo

run-name: ${{ github.actor }} is testing out github actions

on:
  pull_request:
  pull_request_target:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: 'Automated Version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Auth with Tyro Private NPM Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > "${HOME}/.npmrc"
          echo "@tyro-private:registry=https://npm.pkg.github.com" >> "${HOME}/.npmrc"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > "${HOME}/.npmrc"

      - run: npm ci
      - name: Publish NPM
        run: npm publish --provenance --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}